name: first workflow
on: workflow_dispatch
jobs:  
  first-job: 
    runs-on: ubuntu-latest
    container:
      image: node
    services:
      mongodb:
        image: mongo
        env: 
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: password 
    steps: 
      - name: Print greeting
        run: |
          echo "hello world"
          echo "this is multiline testing"
      - name: Print Goodbye
        run: echo "Done - bye"
        
      
