name: first workflow
on: workflow_dispatch
jobs:  
  first-job: 
    runs-on: ubuntu-latest
    steps: 
      - name: Print greeting
        run: |
          echo "hello world"
          echo "this is multiline testing"
      - name: Print Goodbye
        run: echo "Done - bye"
        
      
